package in.co.itlabs.minierp.util;

public enum Stage {
	FIRST_YEAR_ODD_SEM, FIRST_YEAR_EVEN_SEM, SECOND_YEAR_ODD_SEM, SECOND_YEAR_EVEN_SEM, THIRD_YEAR_ODD_SEM,
	THIRD_YEAR_EVEN_SEM, FOURTH_YEAR_ODD_SEM, FOURTH_YEAR_EVEN_SEM
}
